# Generated by Django 5.0.2 on 2024-02-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_json2pdf_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="json2pdf",
            name="json",
            field=models.JSONField(default={}),
        ),
    ]
