# Generated by Django 5.0.2 on 2024-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_json2pdf_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="json2pdf",
            name="json",
            field=models.JSONField(default=dict),
        ),
    ]
