# Generated by Django 5.0.2 on 2024-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_json2pdf_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="json2pdf",
            name="user",
        ),
        migrations.AddField(
            model_name="json2pdf",
            name="Student_Id",
            field=models.CharField(default="studentID", max_length=20, unique=True),
        ),
    ]
