# Generated by Django 5.0.2 on 2024-02-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job_Opening', '0001_initial'),
        ('TrainingProgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('StudentID', models.CharField(max_length=8)),
                ('Email', models.EmailField(max_length=254)),
                ('Branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Engineering')], max_length=50)),
                ('ResumeLink', models.CharField(max_length=300)),
                ('CGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('BlockAllApplications', models.BooleanField()),
                ('AccessToken', models.CharField(max_length=300)),
                ('Placed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_Opening.job_opening')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Student_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blocked', models.BooleanField()),
                ('Status', models.CharField(max_length=1)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_Opening.job_opening')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Training_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attended', models.BooleanField()),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('TrainingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingProgram.trainingprogram')),
            ],
        ),
    ]
