# Generated by Django 5.0.2 on 2024-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_roll',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(default='UI22EC72', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
