# Generated by Django 5.0.1 on 2024-02-15 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(default=uuid.uuid4, max_length=8, unique=True),
        ),
    ]
