# Generated by Django 5.0.2 on 2024-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='student',
            name='LastName',
            field=models.CharField(default='last name', max_length=100),
        ),
    ]
