# Generated by Django 5.0.2 on 2024-02-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opening', '0001_initial'),
        ('student', '0002_rename_name_student_firstname_student_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Placed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Job_Opening.job_opening'),
        ),
    ]
