# Generated by Django 5.0.2 on 2024-02-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_username_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(default='studentID', max_length=20, unique=True),
        ),
    ]
