# Generated by Django 5.0.2 on 2024-02-09 02:37

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_email'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='student',
        #     name='email',
        #     field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='first_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='last_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='username',
        #     field=models.CharField(default='uname', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
