# Generated by Django 5.0.2 on 2024-02-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opening', '0001_initial'),
        ('student', '0003_alter_student_lastname_alter_student_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Placed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Job_Opening.job_opening'),
        ),
    ]
