# Generated by Django 5.0.2 on 2024-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_placed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_student_application',
            old_name='JobID',
            new_name='Job_ID',
        ),
        migrations.RenameField(
            model_name='job_student_application',
            old_name='StudentID',
            new_name='Student_ID',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='AccessToken',
            new_name='Access_Token',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='BlockAllApplications',
            new_name='Block_All_Applications',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ResumeLink',
            new_name='Resume_Link',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StudentID',
            new_name='Student_ID',
        ),
        migrations.RenameField(
            model_name='student_training_registration',
            old_name='StudentID',
            new_name='Student_ID',
        ),
        migrations.RenameField(
            model_name='student_training_registration',
            old_name='TrainingID',
            new_name='Training_ID',
        ),
    ]
