# Generated by Django 5.0.2 on 2024-02-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_email_remove_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
