# Generated by Django 5.0.1 on 2024-02-12 17:56

import allauth.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(default=allauth.account.models.EmailAddress, max_length=8),
        ),
    ]
