# Generated by Django 5.0.2 on 2024-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Access_Token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
