# Generated by Django 5.0.2 on 2024-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
