# Generated by Django 5.0.2 on 2024-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_access_token_alter_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Block_All_Applications',
            field=models.BooleanField(default=False),
        ),
    ]
