# Generated by Django 5.0.2 on 2024-02-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_block_all_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Access_Token',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='Block_All_Applications',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
