# Generated by Django 5.0.2 on 2024-02-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Access_Token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
