# Generated by Django 5.0.1 on 2024-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opening', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_opening',
            old_name='start',
            new_name='end_of_registration',
        ),
        migrations.AddField(
            model_name='job_opening',
            name='join_date',
            field=models.DateField(default='2024-12-05'),
            preserve_default=False,
        ),
    ]
