# Generated by Django 4.1 on 2024-01-31 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job_Opening', '0003_jobapplication_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('user', 'job_opening')},
        ),
    ]
